### PR TITLE
Docops/fix edit button/41

### LINKED ISSUE #41: Edit button redirects to 404
Issue seems to be that Edit button points to `dev` branch, which doesn't exist

### PR DESCRIPTION
**Pull request by capsulecorplab**
closes #41

### CODE REVIEW

**Comment by mmroden** [comment]
Should this go directly to deploy?  Should it go to a branch that we would have to merge in once we accept changes?  How do we do rights management here, are only approved github accounts able to edit?

**Comment by capsulecorplab** [comment]
> Should this go directly to deploy? Should it go to a branch that we would have to merge in once we accept changes? How do we do rights management here, are only approved github accounts able to edit?

we used to have a `dev` branch that served as the staging branch, but it was causing bottlenecks, since there wasn't anyone (besides me) to test local deployments before merging to the `deploy` branch. An alternative workflow would be to setup a CI/CD pipeline where merges to a staging branch would also deploy a preview-able documentation page, but GitHub doesn't support that capability (as far as I know); we would need to set something up like Netlify, which supports [builds on pull requests](https://www.netlify.com/tags/pull-request/)

**Comment by mmroden** [comment]
Is the original assumption I had-- that we want to prevent non-authorized users from making direct changes- the right one?  If so, maybe we just remove the edit button and provide contact info for potential contributors?

**Comment by capsulecorplab** [comment]
Currently, only people with write access to the repo can edit the page directly. The default GitHub behavior for the edit button for anyone without write access is to fork the repo. If we want to enforce that maintainers of the repo have a reviewer for edits, we should add branch protection to the default branch such that edits can only be made via pull requests that require a reviewer

**Review by mmroden — APPROVED** [review]
Approved because it creates a fork for the project for non-approved submitters

**Pull request merged**
