### PR TITLE
Update documentation for makerfaire

### LINKED ISSUE #125: Update documentation for Makerfaire
- [x] take photos of assembling m12 box
- [x] take photos of assembling fan box
- [x] take photos of assembling mask
- [x] take photos of mounting on backpack
- [x] create content around photos of m12
- [x] create content around photos of fan box
- [ ] create content around photos of mask
- [ ] create content around backpack mount
- [x] Have a link to docs on tetrab.io
- [ ] readme will direct to https://tetrabiodistributed.github.io/ from https://github.com/tetrabiodistributed/papra-pcba
- [ ] Update tetrab.io (MMR to do this)
- [ ] link to etsy store -- tetrab.io and main documentation site on landing page of tetrabiodistributed.github.io/

### PR DESCRIPTION
**Pull request by Venkat4real**
closes #125

### CODE REVIEW

**Comment by capsulecorplab** [comment]
Memo: need to fix image not rendering in https://github.com/tetrabiodistributed/papra/pull/128/files#diff-c3d79961838dba1944993cf0a83bbf133252111e05edde07a425e4942cc20296R22

**Comment by capsulecorplab** [comment]
hot-fix seems to be working on my forked repo https://capsulecorplab.github.io/papra/v1.0/papra-pcba/ as of https://github.com/tetrabiodistributed/papra/pull/128/commits/2cc1a9eea66198d53e0862f16a6ac5e09c62a77f

**Comment by mmroden** [comment]
BOM outside of the electronics for the fan box: 13 m4 16mm screws, 13 m4 square nuts, dryer tape, BNC 20 gauge wire stays, stealth filters (https://www.amazon.com/STEALTH-Respirator-Filters-Woodworking-Replacement/dp/B09H52LGGW NOT https://www.amazon.com/Trend-STEALTH-AIR-Filter-pair/dp/B077TX6Q9K for N100, trend passes at N95)

**Comment by mmroden** [comment]
for the m12 assembly: 4 m4 16mm screws with 4 m4 square nuts

**Comment by mmroden** [comment]
For hosing: 1.5 inch heat shrink material, heat gun needed.

**Comment by mmroden** [comment]
Just kidding 1 inch heat shrink tubing

**Comment by mmroden** [comment]
https://octopart.com/bom-tool/AamYg0bD

**Review by capsulecorplab — CHANGES_REQUESTED** [review]
things needed in the fanbox BOM:
- [ ] fan (as part of octopart BOM)13 m4 16mm screws
- [ ] 13 m4 square nuts
- [ ] stealth filters
- [ ] bnc cable (either 1 or 3 feet long, depending on mounting configuration)
- [ ] dryer tape
- [ ] in the end, some kind of mount is needed, either belt or backpack, and the user should figure out what they want.  We're using the Seibertron MOLLE backpack, but any MOLLE backpack/belt will do

**Review by capsulecorplab — APPROVED** [review]

**Pull request merged**
